"""Channel path input and metadata models for SI-TDR automation."""

from .analysis_templates import (
    AnalysisTemplateSelection,
    AnalysisTemplateValidationError,
    apply_default_analysis_templates,
)
from .analysis_options import (
    AnalysisOptionError,
    ResolvedAnalysisOptionCatalog,
    resolve_analysis_option_catalog,
    select_analysis_options,
)
from .direction import (
    MEASUREMENT_DIRECTIONS,
    PATH_ENDPOINT_TO_START,
    PATH_START_TO_ENDPOINT,
    DirectionCandidate,
    DirectionResolution,
    DirectionResolutionError,
    direction_candidate,
    normalize_measurement_direction,
    require_resolved_direction,
    resolve_measurement_direction,
)

from .targets import (
    ChannelTarget,
    ChannelTargetValidationError,
    PortRoleMetadata,
    load_channel_targets_csv,
    write_port_role_metadata,
)
from .aedb_lookup import (
    ChannelPinLookupReport,
    PinLookupRecord,
    PinLookupRequest,
    lookup_channel_target_pins,
    lookup_pin_requests,
    write_pin_lookup_report,
)
from .minimal_input import (
    MinimalChannelInput,
    MinimalInputProfile,
    MinimalInputValidationError,
    MinimalNormalizationResult,
    MinimalTargetOverrides,
    build_minimal_discovery_targets,
    build_minimal_input_pin_requests,
    build_minimal_path_net_evidence,
    canonical_target_key,
    load_minimal_channel_inputs_csv,
    load_minimal_input_profile,
    load_minimal_target_overrides,
    normalize_minimal_inputs,
    write_minimal_normalization_report,
    write_normalized_channel_targets_csv,
)
from .detailed_input import (
    DetailedChannelPair,
    DetailedConductorRow,
    DetailedCsvInput,
    DetailedInputValidationError,
    DetailedNormalizationResult,
    DetailedSnpBatch,
    load_detailed_csv,
    normalize_detailed_csv,
    normalize_detailed_input,
    write_detailed_channel_targets_csv,
    write_detailed_normalization_report,
)
from .array_mapping import (
    ArrayMappingLibrary,
    ArrayPartMapping,
    array_mapping_library_from_customer_catalog,
    load_array_mapping_library,
)
from .customer_components import (
    apply_customer_path_components,
    build_customer_component_contract,
    load_customer_array_catalog,
    plan_customer_path_components,
    resolve_customer_array_catalog,
)
from .part_library import (
    PartLibrarySchemaError,
    load_part_library_entries,
    normalize_part_library_payload,
)
from .path_traversal import (
    ChannelPathReport,
    PolarityPath,
    trace_channel_paths,
    write_channel_path_report,
)
from .series_models import (
    apply_series_models,
    collect_path_series_components,
    load_part_library,
    resolve_treatment,
)
from .tdr_config import build_tdr_config_fragment, write_tdr_config_fragment
from .time_range import (
    TimeRangeResolutionError,
    annotate_resolved_path_routing_length,
    apply_tdr_time_range_resolution,
    resolve_run_config_time_range,
    resolve_tdr_time_range,
    write_time_range_resolution,
)
from .port_metadata import (
    build_port_metadata_from_channel_paths,
    filter_port_metadata_by_config_fragment,
    write_filtered_port_metadata,
    write_port_metadata_from_channel_paths,
)
from .port_contract import (
    ReferenceNetResolutionError,
    build_endpoint_terminal_contract,
    resolve_reference_net_candidate,
    validate_planned_port_contract,
)

__all__ = [
    "AnalysisTemplateSelection",
    "AnalysisTemplateValidationError",
    "AnalysisOptionError",
    "ResolvedAnalysisOptionCatalog",
    "DirectionCandidate",
    "DirectionResolution",
    "DirectionResolutionError",
    "MEASUREMENT_DIRECTIONS",
    "PATH_ENDPOINT_TO_START",
    "PATH_START_TO_ENDPOINT",
    "ChannelPinLookupReport",
    "ChannelPathReport",
    "apply_series_models",
    "collect_path_series_components",
    "load_part_library",
    "resolve_treatment",
    "ChannelTarget",
    "ChannelTargetValidationError",
    "DetailedChannelPair",
    "DetailedConductorRow",
    "DetailedCsvInput",
    "DetailedInputValidationError",
    "DetailedNormalizationResult",
    "DetailedSnpBatch",
    "ArrayMappingLibrary",
    "ArrayPartMapping",
    "array_mapping_library_from_customer_catalog",
    "PartLibrarySchemaError",
    "MinimalChannelInput",
    "MinimalInputProfile",
    "MinimalInputValidationError",
    "MinimalNormalizationResult",
    "MinimalTargetOverrides",
    "PinLookupRecord",
    "PinLookupRequest",
    "PolarityPath",
    "PortRoleMetadata",
    "ReferenceNetResolutionError",
    "TimeRangeResolutionError",
    "apply_default_analysis_templates",
    "apply_customer_path_components",
    "build_customer_component_contract",
    "load_customer_array_catalog",
    "plan_customer_path_components",
    "resolve_customer_array_catalog",
    "resolve_analysis_option_catalog",
    "select_analysis_options",
    "annotate_resolved_path_routing_length",
    "apply_tdr_time_range_resolution",
    "build_tdr_config_fragment",
    "direction_candidate",
    "build_port_metadata_from_channel_paths",
    "build_endpoint_terminal_contract",
    "filter_port_metadata_by_config_fragment",
    "build_minimal_input_pin_requests",
    "build_minimal_discovery_targets",
    "build_minimal_path_net_evidence",
    "canonical_target_key",
    "load_array_mapping_library",
    "load_part_library_entries",
    "normalize_part_library_payload",
    "normalize_measurement_direction",
    "load_channel_targets_csv",
    "load_detailed_csv",
    "load_minimal_channel_inputs_csv",
    "load_minimal_input_profile",
    "load_minimal_target_overrides",
    "lookup_channel_target_pins",
    "lookup_pin_requests",
    "normalize_minimal_inputs",
    "normalize_detailed_csv",
    "normalize_detailed_input",
    "resolve_run_config_time_range",
    "require_resolved_direction",
    "resolve_measurement_direction",
    "resolve_tdr_time_range",
    "resolve_reference_net_candidate",
    "trace_channel_paths",
    "write_channel_path_report",
    "write_pin_lookup_report",
    "write_minimal_normalization_report",
    "write_normalized_channel_targets_csv",
    "write_detailed_channel_targets_csv",
    "write_detailed_normalization_report",
    "write_port_role_metadata",
    "write_tdr_config_fragment",
    "write_time_range_resolution",
    "write_filtered_port_metadata",
    "write_port_metadata_from_channel_paths",
    "validate_planned_port_contract",
]
